"""empty message

Revision ID: 236242514d50
Revises: f8382eff68eb
Create Date: 2020-12-21 09:41:03.590752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236242514d50'
down_revision = 'f8382eff68eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('address', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'address')
    # ### end Alembic commands ###
