"""empty message

Revision ID: f8382eff68eb
Revises: b85829478e05
Create Date: 2020-12-20 18:57:57.255414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8382eff68eb'
down_revision = 'b85829478e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seek_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seek_description')
    # ### end Alembic commands ###
