"""empty message

Revision ID: f8f46cd52821
Revises: 236242514d50
Create Date: 2020-12-21 16:49:21.772592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f46cd52821'
down_revision = '236242514d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('facebook_link', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'facebook_link')
    # ### end Alembic commands ###
